from setuptools import find_packages, setup

setup(
    name="neural_ode",
    version="0.1.0",
    description="Reproduction of 'Neural Ordinary Differential Equations' (arXiv:1806.07366), generated by ArXivist.",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.10",
)
