"""Custom adjoint sensitivity method for backpropagating through an ODE solve.

Implements Algorithm 1 / Algorithm 2 (Appendix C) and the augmented-state
derivation in Appendix B of the paper: instead of backpropagating through the
operations of the forward solver (which RK-Net does), we solve a second,
augmented ODE backwards in time to obtain gradients w.r.t. the initial state,
the dynamics parameters theta, and the integration bounds t0/t1 — all with
O(1) memory cost in the number of solver steps.

    da(t)/dt   = -a(t)^T df/dz                          (Eq. 4)
    dL/dtheta  = -int_{t1}^{t0} a(t)^T df/dtheta dt      (Eq. 5)

WARNING: low-confidence implementation risk (see architecture plan risk
assessment, Medium severity): this from-scratch implementation is provided
for educational/faithfulness purposes. `TorchdiffeqAdaptiveSolver` (via
`ode_block.py`, backend="dopri5") is the RECOMMENDED default for actually
reproducing paper results, since it is the well-tested community reference.
This module's gradients should be validated with `torch.autograd.gradcheck`
before being trusted for research use (see tests/ — not generated by this
pipeline stage, see architecture plan §"What You Must NOT Do").

Architecture plan: src/neural_ode/core/adjoint.py.
"""

from __future__ import annotations

from typing import Sequence, Tuple

import torch
from torch import Tensor

from neural_ode.core.ode_solvers import BaseSolver


def _flatten_params(params: Sequence[Tensor]) -> Tensor:
    return torch.cat([p.reshape(-1) for p in params]) if params else torch.zeros(0)


def _unflatten_like(flat: Tensor, like: Sequence[Tensor]) -> Tuple[Tensor, ...]:
    out = []
    offset = 0
    for p in like:
        n = p.numel()
        out.append(flat[offset : offset + n].view_as(p))
        offset += n
    return tuple(out)


class OdeintAdjointMethod(torch.autograd.Function):
    """torch.autograd.Function implementing Algorithm 1/2 (Appendix C).

    forward(ctx, z0, func, t, solver, *params) -> trajectory [T, B, D]
    backward(ctx, grad_output) -> gradients matching forward's inputs.
    """

    @staticmethod
    def forward(ctx, z0: Tensor, func: torch.nn.Module, t: Tensor, solver: BaseSolver, *params: Tensor) -> Tensor:
        with torch.no_grad():
            trajectory = solver.integrate(lambda tt, zz: func(tt, zz), z0, t)
        ctx.func = func
        ctx.solver = solver
        ctx.save_for_backward(t, trajectory, *params)
        return trajectory

    @staticmethod
    def backward(ctx, grad_output: Tensor):  # noqa: C901 - inherently a multi-part algorithm
        func = ctx.func
        solver = ctx.solver
        t, trajectory, *params = ctx.saved_tensors
        T = t.shape[0]

        # Eq. context / Algorithm 1: augmented state = [z, a, a_theta] (we omit a_t here
        # for simplicity, i.e. we do not return gradients w.r.t. t0/t1; see Appendix C for
        # the full extension with a_t if start/end-time gradients are required).
        a_theta = torch.zeros_like(_flatten_params(params))
        a = grad_output[-1]
        z_final = trajectory[-1]

        def augmented_dynamics(tt: Tensor, aug_state: Tensor) -> Tensor:
            # aug_state packs [z (flattened), a (flattened), a_theta (flattened)] into one vector
            # so a single call to `solver.integrate` advances the whole augmented system,
            # exactly as described just before Algorithm 1 in the paper.
            n_z = z_final.numel()
            n_a = n_z
            z = aug_state[:n_z].view_as(z_final).detach().requires_grad_(True)
            with torch.enable_grad():
                f_val = func(tt, z)
                vjp_z, *vjp_params = torch.autograd.grad(
                    f_val, (z,) + tuple(params), grad_outputs=-aug_state[n_z : n_z + n_a].view_as(f_val),
                    allow_unused=True, retain_graph=False,
                )
            vjp_z = torch.zeros_like(z) if vjp_z is None else vjp_z
            vjp_params_flat = _flatten_params(
                [torch.zeros_like(p) if g is None else g for g, p in zip(vjp_params, params)]
            )
            return torch.cat([f_val.reshape(-1), vjp_z.reshape(-1), vjp_params_flat])

        # Integrate the augmented adjoint ODE backwards between every consecutive pair of
        # observation times (Figure 2: "the reverse-mode derivative must be broken into a
        # sequence of separate solves, one between each consecutive pair of output times").
        for i in range(T - 1, 0, -1):
            aug_state0 = torch.cat([trajectory[i].reshape(-1), a.reshape(-1), a_theta])
            t_span = torch.stack([t[i], t[i - 1]])
            aug_traj = solver.integrate(augmented_dynamics, aug_state0, t_span)
            aug_final = aug_traj[-1]
            n_z = z_final.numel()
            a = aug_final[n_z : 2 * n_z].view_as(z_final)
            a_theta = aug_final[2 * n_z :]
            # Observation at t[i-1] contributes directly to the adjoint (Figure 2: "the
            # adjoint state must be updated in the direction of the partial derivative of
            # the loss with respect to each observation").
            a = a + grad_output[i - 1]

        grad_z0 = a
        grad_params = _unflatten_like(a_theta, params)
        return (grad_z0, None, None, None, *grad_params)


def odeint_adjoint(z0: Tensor, func: torch.nn.Module, t: Tensor, solver: BaseSolver) -> Tensor:
    """Convenience wrapper: run `func`'s parameters through the adjoint method automatically."""
    params = tuple(p for p in func.parameters() if p.requires_grad)
    return OdeintAdjointMethod.apply(z0, func, t, solver, *params)
