"""Absorb-Escape: post-training refinement of DiscDiff sequences (Sec 4.2, Fig 4).

Given a sequence `s` generated by a diffusion decoder D (with per-position confidences
`l_d`) and a pretrained autoregressive model `M`, Absorb-Escape scans for low-confidence
'valleys' and locally re-generates them with M:

    1. ABSORB: at position i where A(s_i) = [L(D,s_i) < T_absorb] is true, enter refinement.
    2. AUTOREGRESSIVE GEN: from position i, generate tokens with M.
    3. ESCAPE: continue until an escape condition E(s_j) holds (default: natural,
       L(D,s_j) > L(M,s_j)), then REPLACE the valley region of s with M's tokens.

The algorithm is model-agnostic: `ar_model` only needs
    - generate(prefix, pos) -> (token, conf)   : next-token id + its max-softmax at `pos`
and is completely defined by the confidence arrays. This makes it CPU-verifiable with
synthetic profiles (no trained weights).
"""
from __future__ import annotations

import random
from dataclasses import dataclass
from typing import List, Optional, Protocol, Sequence, Tuple

from .conditions import (
    absorb_condition,
    escape_max_length,
    escape_natural,
    escape_random,
    escape_threshold,
)


class ARModel(Protocol):
    def generate(self, prefix: List[int], pos: int) -> Tuple[int, float]:
        """Return (next_token_id, max_softmax_confidence) at absolute position `pos`,
        conditioned on `prefix` (tokens 0..pos-1)."""
        ...


@dataclass
class AbsorbEscapeConfig:
    t_absorb: float = 0.9          # absorb when diffusion confidence < this
    escape: str = "natural"        # 'natural' | 'threshold' | 'random' | 'max_length'
    t_escape: float = 0.5          # for escape='threshold'
    t_random: float = 0.9          # for escape='random'
    max_sub_length: int = 32       # for escape='max_length'
    seed: int = 0


def absorb_escape(
    s: Sequence[int],
    l_d: Sequence[float],
    ar_model: ARModel,
    cfg: Optional[AbsorbEscapeConfig] = None,
) -> List[int]:
    """Refine sequence `s` using diffusion confidences `l_d` and AR model `ar_model`.

    Returns the refined token sequence (same length as `s`).
    """
    cfg = cfg or AbsorbEscapeConfig()
    rng = random.Random(cfg.seed)
    out = list(s)
    n = len(out)
    i = 0

    while i < n:
        # (1) ABSORB: skip confident positions
        if not absorb_condition(l_d[i], cfg.t_absorb):
            i += 1
            continue

        # (2) AUTOREGRESSIVE GENERATION from position i until escape
        start = i
        j = i
        while j < n:
            token, l_m_j = ar_model.generate(out[:j], j)
            out[j] = token  # replace the low-probability nucleotide (Fig 4 'Replace')

            # (3) ESCAPE test at j
            if cfg.escape == "natural":
                stop = escape_natural(l_d[j], l_m_j)
            elif cfg.escape == "threshold":
                stop = escape_threshold(l_m_j, cfg.t_escape)
            elif cfg.escape == "random":
                stop = escape_random(cfg.t_random, rng)
            elif cfg.escape == "max_length":
                stop = escape_max_length(j, start, cfg.max_sub_length)
            else:
                raise ValueError(f"unknown escape mode: {cfg.escape}")

            j += 1
            if stop:
                break

        i = max(j, start + 1)  # resume scanning after the refined region
    return out
