from setuptools import find_packages, setup

setup(
    name="d3lm",
    version="0.1.0",
    description="Reproduction of D3LM (arXiv:2603.01780), generated by ArXivist",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.1",
        "transformers>=4.38,<4.46",
        "accelerate>=0.30",
        "datasets>=2.14",
        "huggingface_hub>=0.19",
        "python-Levenshtein>=0.21",
        "scikit-learn>=1.3",
        "scipy>=1.10",
        "numpy>=1.24",
        "pandas>=2.0",
        "pyyaml>=6.0",
        "tqdm>=4.66",
    ],
)
